<?php

declare(strict_types=1);

return [
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Cart\CartBehavior',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 2,
        'parameter' => 'isRecalculation',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Cart\CartException',
        'method' => 'invalidPriceFieldTypeException',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Cart\CartException|Shopware\Core\Framework\DataAbstractionLayer\Exception\InvalidPriceFieldTypeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Cart\CartException',
        'method' => 'unsupportedOperator',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Cart\CartException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Cart\Order\Transformer\CartTransformer',
        'method' => 'transform',
        'kind' => 'rename_parameter',
        'position' => 3,
        'parameter' => 'setOrderDate',
        'newName' => 'setPersistentData',
        'parametersBefore' => [
            [
                'name' => 'cart',
                'hasDefault' => false,
            ],
            [
                'name' => 'context',
                'hasDefault' => false,
            ],
            [
                'name' => 'stateId',
                'hasDefault' => false,
            ],
        ],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Cart\SalesChannel\AbstractCartLoadRoute',
        'method' => 'load',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'cart',
        'type' => '?Shopware\Core\Checkout\Cart\Cart',
        'default' => null,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerEntity',
        'method' => 'setActiveBillingAddress',
        'kind' => 'widen_parameter_type',
        'parameter' => 'activeBillingAddress',
        'currentType' => 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
        'type' => '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerEntity',
        'method' => 'setActiveShippingAddress',
        'kind' => 'widen_parameter_type',
        'parameter' => 'activeShippingAddress',
        'currentType' => 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
        'type' => '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'invalidOption',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|InvalidArgumentException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'missingOption',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|Symfony\Component\Validator\Exception\MissingOptionsException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'productNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Content\Product\Exception\ProductNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'unexpectedType',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|Symfony\Component\Validator\Exception\UnexpectedTypeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'unsupportedOperator',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
        'method' => 'unsupportedValue',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Customer\CustomerException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\SalesChannel\ImitateCustomerRoute',
        'method' => 'imitateCustomerLogin',
        'kind' => 'rename_parameter',
        'position' => 0,
        'parameter' => 'requestDataBag',
        'newName' => 'data',
        'parametersBefore' => [],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerEmailUnique',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerPasswordMatches',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerVatIdentification',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Customer\Validation\Constraint\CustomerZipCode',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Document\DocumentEntity',
        'method' => 'setOrderId',
        'kind' => 'widen_parameter_type',
        'parameter' => 'orderId',
        'currentType' => 'string',
        'type' => '?string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Document\DocumentEntity',
        'method' => 'setOrderVersionId',
        'kind' => 'widen_parameter_type',
        'parameter' => 'orderVersionId',
        'currentType' => 'string',
        'type' => '?string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Document\Zugferd\ZugferdDocument',
        'method' => 'getContent',
        'kind' => 'add_required_parameter',
        'position' => 1,
        'parameter' => 'calculator',
        'type' => 'Shopware\Core\Checkout\Cart\Price\AmountCalculator',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Order\OrderException',
        'method' => 'associationNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Order\OrderException|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
        'method' => 'getPaymentMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
        'method' => 'getReason',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Promotion\PromotionException',
        'method' => 'discountCalculatorNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Promotion\PromotionException|Shopware\Core\Checkout\Promotion\Exception\DiscountCalculatorNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Promotion\PromotionException',
        'method' => 'invalidScopeDefinition',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Checkout\Promotion\PromotionException|Shopware\Core\Checkout\Promotion\Exception\InvalidScopeDefinitionException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
        'method' => 'getReason',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
        'method' => 'getShippingMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Category\CategoryException',
        'method' => 'pageNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\ShopwareHttpException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Cms\Events\CmsPageLoadedEvent',
        'method' => 'getResult',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\EntityCollection',
        'type' => 'Shopware\Core\Content\Cms\CmsPageCollection',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Flow\FlowException',
        'method' => 'customTriggerByNameNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Content\Flow\FlowException|Shopware\Core\Content\Flow\Exception\CustomTriggerByNameNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
        'method' => 'getMediaThumbnailSizeId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
        'method' => 'setUrl',
        'kind' => 'widen_parameter_type',
        'parameter' => 'url',
        'currentType' => 'string',
        'type' => '?string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Media\Thumbnail\ThumbnailService',
        'method' => 'updateThumbnails',
        'kind' => 'add_optional_parameter',
        'position' => 3,
        'parameter' => 'force',
        'type' => 'bool',
        'default' => false,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\ProductExport\Struct\ProductExportResult',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 2,
        'parameter' => 'total',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Product\ProductException',
        'method' => 'missingRequestParameter',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Content\Product\ProductException|Shopware\Core\Framework\Routing\RoutingException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Product\ProductException',
        'method' => 'reviewNotActive',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Content\Product\ProductException|Shopware\Core\Content\Product\Exception\ReviewNotActiveExeption',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Product\SalesChannel\Review\Event\ReviewFormEvent',
        'method' => 'getProduct',
        'kind' => 'narrow_return_type',
        'currentType' => '?Shopware\Core\Content\Product\ProductEntity',
        'type' => 'Shopware\Core\Content\Product\ProductEntity',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Product\SalesChannel\Sorting\ProductSortingEntity',
        'method' => 'createDalSorting',
        'kind' => 'add_optional_parameter',
        'position' => 0,
        'parameter' => 'fallbackSorting',
        'type' => '?Shopware\Core\Framework\DataAbstractionLayer\Search\Sorting\FieldSorting',
        'default' => null,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Content\Property\PropertyGroupCollection',
        'method' => 'sortByConfig',
        'kind' => 'add_required_parameter',
        'position' => 0,
        'parameter' => 'localeCode',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Adapter\AdapterException',
        'method' => 'unsupportedOperator',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Adapter\AdapterException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Adapter\Twig\Extension\NodeExtension',
        'method' => '__construct',
        'kind' => 'widen_parameter_type',
        'parameter' => 'finder',
        'currentType' => 'Shopware\Core\Framework\Adapter\Twig\TemplateFinder',
        'type' => 'Shopware\Core\Framework\Adapter\Twig\TemplateFinderInterface',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Api\ApiException',
        'method' => 'apiDefinitionGeneratorNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Api\ApiException|Shopware\Core\Framework\Api\ApiDefinition\ApiDefinitionGeneratorNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Context',
        'method' => 'scope',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'states',
        'type' => 'array',
        'default' => [],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'cannotBuildAccessor',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'configNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Elasticsearch\Product\ElasticsearchProductException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'invalidSyncOperationException',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Core\Framework\Api\Exception\InvalidSyncOperationException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'missingTranslatedStorageAwareProperty',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'missingVersionField',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'noTranslationDefinition',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'onlyStorageAwareFieldsAsTranslated',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'onlyStorageAwareFieldsInReadCondition',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'primaryKeyNotStorageAware',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'unexpectedFieldType',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
        'method' => 'unmappedField',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException|Shopware\Core\Framework\DataAbstractionLayer\Dbal\Exception\UnmappedFieldException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway',
        'method' => 'prefetchExistences',
        'kind' => 'rename_parameter',
        'position' => 0,
        'parameter' => 'parameters',
        'newName' => 'parameterBag',
        'parametersBefore' => [],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Event\EntityWrittenContainerEvent',
        'method' => 'getEvents',
        'kind' => 'narrow_return_type',
        'currentType' => '?Shopware\Core\Framework\Event\NestedEventCollection',
        'type' => 'Shopware\Core\Framework\Event\NestedEventCollection',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\CreatedByField',
        'method' => '__construct',
        'kind' => 'explicit_current_default',
        'position' => 0,
        'parameter' => 'allowedWriteScopes',
        'default' => [
            'system',
        ],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'method' => 'addFlags',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'type' => 'static',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'method' => 'removeFlag',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'type' => 'static',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'method' => 'setDescription',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'type' => 'static',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'method' => 'setFlags',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
        'type' => 'static',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\LockedField',
        'method' => '__construct',
        'kind' => 'add_optional_parameter',
        'position' => 0,
        'parameter' => 'lockTranslation',
        'type' => 'bool',
        'default' => true,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\UpdatedByField',
        'method' => '__construct',
        'kind' => 'explicit_current_default',
        'position' => 0,
        'parameter' => 'allowedWriteScopes',
        'default' => [
            'system',
        ],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer',
        'method' => 'tokenize',
        'kind' => 'add_optional_parameter',
        'position' => 1,
        'parameter' => 'tokenMinimumLength',
        'type' => '?int',
        'default' => null,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\TokenizerInterface',
        'method' => 'tokenize',
        'kind' => 'add_optional_parameter',
        'position' => 1,
        'parameter' => 'tokenMinimumLength',
        'type' => '?int',
        'default' => null,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Validation\EntityExists',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Validation\EntityNotExists',
        'method' => '__construct',
        'kind' => 'remove_parameter',
        'position' => 0,
        'parameter' => 'options',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Event\NestedEventCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\FrameworkException',
        'method' => 'associationNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\FrameworkException|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\FrameworkException',
        'method' => 'createFromError',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\FrameworkException|InvalidArgumentException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Plugin\PluginException',
        'method' => 'kernelPluginLoaderError',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\KernelPluginLoaderException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Plugin\PluginException',
        'method' => 'pluginComposerRemove',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\PluginComposerRemoveException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Plugin\PluginException',
        'method' => 'pluginComposerRequire',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Plugin\PluginException|Shopware\Core\Framework\Plugin\Exception\PluginComposerRequireException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Routing\RoutingException',
        'method' => 'missingMainRequest',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Routing\RoutingException|InvalidArgumentException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Rule\RuleComparison',
        'method' => 'date',
        'kind' => 'widen_parameter_type',
        'parameter' => 'ruleValue',
        'currentType' => 'DateTime',
        'type' => '\DateTime|string|array',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Rule\RuleComparison',
        'method' => 'datetime',
        'kind' => 'widen_parameter_type',
        'parameter' => 'ruleValue',
        'currentType' => 'DateTime',
        'type' => '\DateTime|string|array',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Rule\RuleException',
        'method' => 'ruleNameNotImplemented',
        'kind' => 'narrow_return_type',
        'currentType' => 'Error|Shopware\Core\Framework\Rule\RuleException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Rule\RuleException',
        'method' => 'unsupportedOperator',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Rule\RuleException|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Rule\RuleException',
        'method' => 'unsupportedValue',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Rule\RuleException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\StoreException',
        'method' => 'invalidContextSourceUser',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Api\Context\Exception\InvalidContextSourceUserException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\StoreException',
        'method' => 'invalidCredentials',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Store\Exception\StoreInvalidCredentialsException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\StoreException',
        'method' => 'jwksNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\App\AppException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\StoreException',
        'method' => 'pluginNotAZipFile',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Plugin\Exception\PluginNotAZipFileException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\StoreException',
        'method' => 'shopSecretInvalid',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Store\StoreException|Shopware\Core\Framework\Store\Exception\ShopSecretInvalidException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\BinaryCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\DomainVerificationRequestStruct',
        'method' => '__construct',
        'kind' => 'rename_parameter',
        'position' => 1,
        'parameter' => 'filename',
        'newName' => 'fileName',
        'parametersBefore' => [
            [
                'name' => 'content',
                'hasDefault' => false,
            ],
        ],
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\FaqCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\ImageCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\PermissionCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\ReviewCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\StoreCategoryCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\StoreCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Store\Struct\VariantCollection',
        'method' => 'getExpectedClass',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Util\UtilException',
        'method' => 'operatorNotSupported',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Util\UtilException|Shopware\Core\Framework\Util\Exception\ComparatorException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Validation\ValidatorFactory',
        'method' => 'create',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'allowExtraFields',
        'type' => 'bool',
        'default' => false,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Webhook\Service\WebhookDeliveryService',
        'method' => 'process',
        'kind' => 'remove_parameter',
        'position' => 1,
        'parameter' => 'forceSynchronous',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Webhook\WebhookException',
        'method' => 'invalidDataMapping',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Webhook\WebhookException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\Framework\Webhook\WebhookException',
        'method' => 'unknownEventDataType',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\Framework\Webhook\WebhookException|RuntimeException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\Language\LanguageException',
        'method' => 'unsupportedValue',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\System\Language\LanguageException|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\NumberRange\NumberRangeException',
        'method' => 'incrementStorageNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\System\NumberRange\NumberRangeException|Shopware\Core\System\NumberRange\Exception\IncrementStorageNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\SalesChannel\SalesChannelException',
        'method' => 'missingAssociation',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\System\SalesChannel\SalesChannelException|Shopware\Core\Checkout\Order\OrderException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\SalesChannel\SalesChannelException',
        'method' => 'orderNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Core\System\SalesChannel\SalesChannelException|Shopware\Core\Checkout\Order\OrderException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\Snippet\SnippetFixer',
        'method' => 'fix',
        'kind' => 'add_required_parameter',
        'position' => 1,
        'parameter' => 'invalidPluralization',
        'type' => 'Shopware\Core\System\Snippet\Struct\InvalidPluralizationCollection',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
        'method' => 'delete',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'silent',
        'type' => 'bool',
        'default' => true,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
        'method' => 'set',
        'kind' => 'add_optional_parameter',
        'position' => 3,
        'parameter' => 'silent',
        'type' => 'bool',
        'default' => true,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
        'method' => 'setMultiple',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'silent',
        'type' => 'bool',
        'default' => true,
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Elasticsearch\ElasticsearchException',
        'method' => 'operatorNotAllowed',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Elasticsearch\ElasticsearchException|InvalidArgumentException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
        'method' => 'getNewPaymentMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
        'method' => 'getOldPaymentMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
        'method' => 'getReason',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
        'method' => 'getNewShippingMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
        'method' => 'getOldShippingMethodId',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
        'method' => 'getReason',
        'kind' => 'narrow_return_type',
        'currentType' => '?string',
        'type' => 'string',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Controller\Exception\StorefrontException',
        'method' => 'domainNotFound',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Storefront\Controller\Exception\StorefrontException|Shopware\Core\Content\Newsletter\Exception\SalesChannelDomainNotFoundException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Framework\StorefrontFrameworkException',
        'method' => 'mediaValidatorMissing',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Storefront\Framework\StorefrontFrameworkException|Shopware\Storefront\Framework\Media\Exception\MediaValidatorMissingException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Theme\Exception\ThemeException',
        'method' => 'invalidThemeBundle',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Storefront\Theme\Exception\ThemeException|Shopware\Storefront\Theme\Exception\InvalidThemeBundleException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Theme\Exception\ThemeException',
        'method' => 'themeAssignmentException',
        'kind' => 'narrow_return_type',
        'currentType' => 'Shopware\Storefront\Theme\Exception\ThemeException|Shopware\Storefront\Theme\Exception\ThemeAssignmentException',
        'type' => 'self',
    ],
    [
        'version' => 'v6.8.0',
        'class' => 'Shopware\Storefront\Theme\ThemeLifecycleService',
        'method' => 'refreshTheme',
        'kind' => 'add_optional_parameter',
        'position' => 2,
        'parameter' => 'configurationCollection',
        'type' => '?Shopware\Storefront\Theme\StorefrontPluginConfiguration\StorefrontPluginConfigurationCollection',
        'default' => null,
    ],
];
