<?php

declare(strict_types=1);

use Frosh\Rector\Rule\BCChange\FutureCompatibleBCChangeRector;
use Rector\Config\RectorConfig;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(
        FutureCompatibleBCChangeRector::class,
        [
            [
                'class' => 'Shopware\Core\Checkout\Cart\CartException',
                'method' => 'invalidPriceFieldTypeException',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\DataAbstractionLayer\Exception\InvalidPriceFieldTypeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Cart\CartException',
                'method' => 'unsupportedOperator',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Cart\SalesChannel\AbstractCartLoadRoute',
                'method' => 'load',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'cart',
                'type' => '?Shopware\Core\Checkout\Cart\Cart',
                'default' => null,
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerEntity',
                'method' => 'setActiveBillingAddress',
                'kind' => 'widen_parameter_type',
                'parameter' => 'activeBillingAddress',
                'currentType' => 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
                'type' => '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerEntity',
                'method' => 'setActiveShippingAddress',
                'kind' => 'widen_parameter_type',
                'parameter' => 'activeShippingAddress',
                'currentType' => 'Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
                'type' => '?Shopware\Core\Checkout\Customer\Aggregate\CustomerAddress\CustomerAddressEntity',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'invalidOption',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|InvalidArgumentException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'missingOption',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Symfony\Component\Validator\Exception\MissingOptionsException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'productNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Content\Product\Exception\ProductNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'unexpectedType',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Symfony\Component\Validator\Exception\UnexpectedTypeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'unsupportedOperator',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Customer\CustomerException',
                'method' => 'unsupportedValue',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Document\DocumentEntity',
                'method' => 'setOrderId',
                'kind' => 'widen_parameter_type',
                'parameter' => 'orderId',
                'currentType' => 'string',
                'type' => '?string',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Document\DocumentEntity',
                'method' => 'setOrderVersionId',
                'kind' => 'widen_parameter_type',
                'parameter' => 'orderVersionId',
                'currentType' => 'string',
                'type' => '?string',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Order\OrderException',
                'method' => 'associationNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
                'method' => 'getPaymentMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Payment\Cart\Error\PaymentMethodBlockedError',
                'method' => 'getReason',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Promotion\PromotionException',
                'method' => 'discountCalculatorNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Checkout\Promotion\Exception\DiscountCalculatorNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Promotion\PromotionException',
                'method' => 'invalidScopeDefinition',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Checkout\Promotion\Exception\InvalidScopeDefinitionException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
                'method' => 'getReason',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Checkout\Shipping\Cart\Error\ShippingMethodBlockedError',
                'method' => 'getShippingMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Content\Category\CategoryException',
                'method' => 'pageNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'Shopware\Core\Framework\ShopwareHttpException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Content\Cms\Events\CmsPageLoadedEvent',
                'method' => 'getResult',
                'kind' => 'narrow_return_type',
                'currentType' => 'Shopware\Core\Framework\DataAbstractionLayer\EntityCollection',
                'type' => 'Shopware\Core\Content\Cms\CmsPageCollection',
            ],
            [
                'class' => 'Shopware\Core\Content\Flow\FlowException',
                'method' => 'customTriggerByNameNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Content\Flow\Exception\CustomTriggerByNameNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
                'method' => 'getMediaThumbnailSizeId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity',
                'method' => 'setUrl',
                'kind' => 'widen_parameter_type',
                'parameter' => 'url',
                'currentType' => 'string',
                'type' => '?string',
            ],
            [
                'class' => 'Shopware\Core\Content\Media\Thumbnail\ThumbnailService',
                'method' => 'updateThumbnails',
                'kind' => 'add_optional_parameter',
                'position' => 3,
                'parameter' => 'force',
                'type' => 'bool',
                'default' => false,
            ],
            [
                'class' => 'Shopware\Core\Content\Product\ProductException',
                'method' => 'missingRequestParameter',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Routing\RoutingException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Content\Product\ProductException',
                'method' => 'reviewNotActive',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Content\Product\Exception\ReviewNotActiveExeption',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Content\Product\SalesChannel\Review\Event\ReviewFormEvent',
                'method' => 'getProduct',
                'kind' => 'narrow_return_type',
                'currentType' => '?Shopware\Core\Content\Product\ProductEntity',
                'type' => 'Shopware\Core\Content\Product\ProductEntity',
            ],
            [
                'class' => 'Shopware\Core\Content\Product\SalesChannel\Sorting\ProductSortingEntity',
                'method' => 'createDalSorting',
                'kind' => 'add_optional_parameter',
                'position' => 0,
                'parameter' => 'fallbackSorting',
                'type' => '?Shopware\Core\Framework\DataAbstractionLayer\Search\Sorting\FieldSorting',
                'default' => null,
            ],
            [
                'class' => 'Shopware\Core\Framework\Adapter\AdapterException',
                'method' => 'unsupportedOperator',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Adapter\Twig\Extension\NodeExtension',
                'method' => '__construct',
                'kind' => 'widen_parameter_type',
                'parameter' => 'finder',
                'currentType' => 'Shopware\Core\Framework\Adapter\Twig\TemplateFinder',
                'type' => 'Shopware\Core\Framework\Adapter\Twig\TemplateFinderInterface',
            ],
            [
                'class' => 'Shopware\Core\Framework\Api\ApiException',
                'method' => 'apiDefinitionGeneratorNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Api\ApiDefinition\ApiDefinitionGeneratorNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Context',
                'method' => 'scope',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'states',
                'type' => 'array',
                'default' => [],
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'cannotBuildAccessor',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'configNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Elasticsearch\Product\ElasticsearchProductException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'invalidSyncOperationException',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Api\Exception\InvalidSyncOperationException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'missingTranslatedStorageAwareProperty',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'missingVersionField',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'noTranslationDefinition',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'onlyStorageAwareFieldsAsTranslated',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'onlyStorageAwareFieldsInReadCondition',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'primaryKeyNotStorageAware',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'unexpectedFieldType',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\DataAbstractionLayerException',
                'method' => 'unmappedField',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\DataAbstractionLayer\Dbal\Exception\UnmappedFieldException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Event\EntityWrittenContainerEvent',
                'method' => 'getEvents',
                'kind' => 'narrow_return_type',
                'currentType' => '?Shopware\Core\Framework\Event\NestedEventCollection',
                'type' => 'Shopware\Core\Framework\Event\NestedEventCollection',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\CreatedByField',
                'method' => '__construct',
                'kind' => 'explicit_current_default',
                'position' => 0,
                'parameter' => 'allowedWriteScopes',
                'default' => [
                    'system',
                ],
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
                'method' => 'addFlags',
                'kind' => 'narrow_return_type',
                'currentType' => 'self',
                'type' => 'static',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
                'method' => 'removeFlag',
                'kind' => 'narrow_return_type',
                'currentType' => 'self',
                'type' => 'static',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
                'method' => 'setDescription',
                'kind' => 'narrow_return_type',
                'currentType' => 'self',
                'type' => 'static',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\Field',
                'method' => 'setFlags',
                'kind' => 'narrow_return_type',
                'currentType' => 'self',
                'type' => 'static',
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\LockedField',
                'method' => '__construct',
                'kind' => 'add_optional_parameter',
                'position' => 0,
                'parameter' => 'lockTranslation',
                'type' => 'bool',
                'default' => true,
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Field\UpdatedByField',
                'method' => '__construct',
                'kind' => 'explicit_current_default',
                'position' => 0,
                'parameter' => 'allowedWriteScopes',
                'default' => [
                    'system',
                ],
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer',
                'method' => 'tokenize',
                'kind' => 'add_optional_parameter',
                'position' => 1,
                'parameter' => 'tokenMinimumLength',
                'type' => '?int',
                'default' => null,
            ],
            [
                'class' => 'Shopware\Core\Framework\DataAbstractionLayer\Search\Term\TokenizerInterface',
                'method' => 'tokenize',
                'kind' => 'add_optional_parameter',
                'position' => 1,
                'parameter' => 'tokenMinimumLength',
                'type' => '?int',
                'default' => null,
            ],
            [
                'class' => 'Shopware\Core\Framework\Event\NestedEventCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\FrameworkException',
                'method' => 'associationNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\DataAbstractionLayer\Exception\AssociationNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\FrameworkException',
                'method' => 'createFromError',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|InvalidArgumentException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Plugin\PluginException',
                'method' => 'kernelPluginLoaderError',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Plugin\Exception\KernelPluginLoaderException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Plugin\PluginException',
                'method' => 'pluginComposerRemove',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Plugin\Exception\PluginComposerRemoveException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Plugin\PluginException',
                'method' => 'pluginComposerRequire',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Plugin\Exception\PluginComposerRequireException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Routing\RoutingException',
                'method' => 'missingMainRequest',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|InvalidArgumentException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Rule\RuleComparison',
                'method' => 'date',
                'kind' => 'widen_parameter_type',
                'parameter' => 'ruleValue',
                'currentType' => 'DateTime',
                'type' => '\DateTime|string|array',
            ],
            [
                'class' => 'Shopware\Core\Framework\Rule\RuleComparison',
                'method' => 'datetime',
                'kind' => 'widen_parameter_type',
                'parameter' => 'ruleValue',
                'currentType' => 'DateTime',
                'type' => '\DateTime|string|array',
            ],
            [
                'class' => 'Shopware\Core\Framework\Rule\RuleException',
                'method' => 'ruleNameNotImplemented',
                'kind' => 'narrow_return_type',
                'currentType' => 'Error|self',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Rule\RuleException',
                'method' => 'unsupportedOperator',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedOperatorException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Rule\RuleException',
                'method' => 'unsupportedValue',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\StoreException',
                'method' => 'invalidContextSourceUser',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Api\Context\Exception\InvalidContextSourceUserException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\StoreException',
                'method' => 'invalidCredentials',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Store\Exception\StoreInvalidCredentialsException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\StoreException',
                'method' => 'jwksNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\App\AppException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\StoreException',
                'method' => 'pluginNotAZipFile',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Plugin\Exception\PluginNotAZipFileException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\StoreException',
                'method' => 'shopSecretInvalid',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Store\Exception\ShopSecretInvalidException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\BinaryCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\FaqCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\ImageCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\PermissionCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\ReviewCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\StoreCategoryCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\StoreCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Store\Struct\VariantCollection',
                'method' => 'getExpectedClass',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Core\Framework\Util\UtilException',
                'method' => 'operatorNotSupported',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Util\Exception\ComparatorException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Validation\ValidatorFactory',
                'method' => 'create',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'allowExtraFields',
                'type' => 'bool',
                'default' => false,
            ],
            [
                'class' => 'Shopware\Core\Framework\Webhook\WebhookException',
                'method' => 'invalidDataMapping',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\Framework\Webhook\WebhookException',
                'method' => 'unknownEventDataType',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|RuntimeException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\System\Language\LanguageException',
                'method' => 'unsupportedValue',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Framework\Rule\Exception\UnsupportedValueException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\System\NumberRange\NumberRangeException',
                'method' => 'incrementStorageNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\System\NumberRange\Exception\IncrementStorageNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\System\SalesChannel\SalesChannelException',
                'method' => 'missingAssociation',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Checkout\Order\OrderException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\System\SalesChannel\SalesChannelException',
                'method' => 'orderNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Checkout\Order\OrderException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
                'method' => 'delete',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'silent',
                'type' => 'bool',
                'default' => true,
            ],
            [
                'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
                'method' => 'set',
                'kind' => 'add_optional_parameter',
                'position' => 3,
                'parameter' => 'silent',
                'type' => 'bool',
                'default' => true,
            ],
            [
                'class' => 'Shopware\Core\System\SystemConfig\SystemConfigService',
                'method' => 'setMultiple',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'silent',
                'type' => 'bool',
                'default' => true,
            ],
            [
                'class' => 'Shopware\Elasticsearch\ElasticsearchException',
                'method' => 'operatorNotAllowed',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|InvalidArgumentException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
                'method' => 'getNewPaymentMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
                'method' => 'getOldPaymentMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\PaymentMethodChangedError',
                'method' => 'getReason',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
                'method' => 'getNewShippingMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
                'method' => 'getOldShippingMethodId',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Checkout\Cart\Error\ShippingMethodChangedError',
                'method' => 'getReason',
                'kind' => 'narrow_return_type',
                'currentType' => '?string',
                'type' => 'string',
            ],
            [
                'class' => 'Shopware\Storefront\Controller\Exception\StorefrontException',
                'method' => 'domainNotFound',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Core\Content\Newsletter\Exception\SalesChannelDomainNotFoundException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Storefront\Framework\StorefrontFrameworkException',
                'method' => 'mediaValidatorMissing',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Storefront\Framework\Media\Exception\MediaValidatorMissingException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Storefront\Theme\Exception\ThemeException',
                'method' => 'invalidThemeBundle',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Storefront\Theme\Exception\InvalidThemeBundleException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Storefront\Theme\Exception\ThemeException',
                'method' => 'themeAssignmentException',
                'kind' => 'narrow_return_type',
                'currentType' => 'self|Shopware\Storefront\Theme\Exception\ThemeAssignmentException',
                'type' => 'self',
            ],
            [
                'class' => 'Shopware\Storefront\Theme\ThemeLifecycleService',
                'method' => 'refreshTheme',
                'kind' => 'add_optional_parameter',
                'position' => 2,
                'parameter' => 'configurationCollection',
                'type' => '?Shopware\Storefront\Theme\StorefrontPluginConfiguration\StorefrontPluginConfigurationCollection',
                'default' => null,
            ],
        ],
    );
};
